services:
  - type: web
    name: myportfolio
    env: python
    buildCommand: "./build.sh"
                  "pip install -r requirements.txt"
                  "python manage.py collectstatic --noinput"
    startCommand: "gunicorn myportfolio.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myportfolio.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "False"
